# Prepare
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/scratch

- name: Download Scratch
  unarchive:
    src: "{{scratch_download_url}}"
    dest: /data/wwwroot
    remote_src: yes

- name: Rename dir name
  shell: cd /data/wwwroot; if [ $( ls | grep "scratch-gui") ]; then mv scratch-gui* scratch; fi

- name: Installation dependency and Build
  shell: sudo npm install && sudo npm run build
  args:
    chdir: /data/wwwroot/scratch

- name: set website for nginx
  copy: 
    src: default
    dest: /etc/nginx/conf.d/default.conf

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  

# Check version
- block:
  - name: Check Erlang Version
    shell: sudo sh -c 'echo "find it form https://github.com/LLK/scratch-gui/releases" 1>> /data/logs/install_version.txt'
